### ISSUE TITLE
Getting error that the owl "must be an rdflib term"

### ISSUE THREAD

**Issue by shola-lawal** [RobotLabLTH/SkiROS2#83]
Hi,

I am getting a must be an rdflib term errors. An example of the error message looks like this, "_Subject http://www.inf.ufrgs.br/phi-group/ontologies/cora.owl#Robot-1 must be an rdflib term_". It doesn't seem that the errors are due to the skiros.owl and skirosExtra.owl files but rather from the owl files in the IEEE-1872-2015 folder. However, this doesn't make sense because I am able to view the owl files from the IEEE-1872-2015 folder in Protégé 5.6.3.

I have attached to outputs below.

Please also note that there are **_SyntaxWarning: "is" with a literal. Did you mean "==**"?_ errors but this is related to python 3.8 raising a SyntaxWarning due to the usage of "is" instead of "==".  

![GetImage](https://github.com/RVMI/skiros2/assets/8649132/72742712-580e-4b50-b9c7-cbb2cc471b0d)
![GetImage1](https://github.com/RVMI/skiros2/assets/8649132/f909a719-bb50-4dcd-98a0-bb1c00b9a936)
![GetImage2](https://github.com/RVMI/skiros2/assets/8649132/391aa4ae-262d-4863-9e5f-c2bbe0d0e900)

Environment:
Ubuntu 20.04.6
Python 3.8.10
ROS Noetic
rdflib 7.0.0

Please advise.
Thank you.

**Comment by matthias-mayr** [comment]
Thank you very much for reporting this.

The Syntax warning seems easy to fix. Interestingly enough, I haven't seen it with my noetic setups. I should take a look at the python versions those use.

For the `rdflib`-error, can you attach the turtle file of your scene? [Here in the user interface](https://raw.githubusercontent.com/wiki/RVMI/skiros2/imgs/edit_world_model.png) is a `Save Scene` button. That would help to debug it.

**Comment by shola-lawal** [comment]
Hi @matthias-mayr,

Here is the turtle sim scene:

(Terminal 1) 
$ roscore 

(Terminal 2) 
$ roslaunch skiros2_examples turtlesim_example.launch 

I just added an empty scene after running the skiros2.

Below is the image:

![skillros](https://github.com/RVMI/skiros2/assets/8649132/c7a0a740-e05e-4030-a431-ed2901c750f5)

**Comment by matthias-mayr** [comment]
Thanks for the instructions. It looks like RDFlib in version 7.0.0 introduced some breaking changes. Until this  is resolved, you can switch to the previous version with
```
pip3 install rdflib==6.3.2
```

**Comment by shola-lawal** [comment]
Amazing, thank you it works now!!

**Comment by matthias-mayr** [comment]
Thanks for the feedback.

I am reopening this issue, because it's only a fix and currently not even enforced by the installation procedure.

**Comment by matthias-mayr** [comment]
Chances are that #90 fixes this.

> Please also note that there are _SyntaxWarning: "is" with a literal. Did you mean "=="?_ errors but this is related to python 3.8 raising a SyntaxWarning due to the usage of "is" instead of "==".

Thanks for bringing up the warning. It is fixed now in 8b11b9e0df03c1583c4af5b4dff18020309eddf8.

**Comment by marcusklang** [comment]
Merged in ros2-develop and seems fixed, recreate issue if not fixed.
